<a href="https://colab.research.google.com/github/haunpapa/oz_class/blob/main/Django/DAY5/1_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Numpy

    - 파이썬에서 수학적인 계산(행렬,벡터,자원)을 편하게 할 수 있도록 돕는 라이브러리

In [1]:
%pip install numpy

In [2]:
import numpy as np


In [6]:
# 1차원 행렬
arr1 = np.array([1,2,3])

arr1
type(arr1)
arr1.shape
arr1.ndim

1

In [9]:
# 2차원 배열
arr2 = np.array([[1,2,3],[4,5,6]])

arr2
arr2.shape
arr2.ndim


2

In [16]:
#ndarray 데이터 타입

arr3 =['1','2','3']

arr3 = np.array(arr3)
arr3 = arr3.astype(np.int64)
arr3.dtype

dtype('int64')

In [21]:
# ndarray 생성
arr = np.arange(10)

arr > 5
arr[arr>5]

array([6, 7, 8, 9])

In [27]:
np.zeros((3,2))
np.ones((3,2))
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [30]:
# reshape ==> 차원 변경
arr = np.arange(10)

arr.reshape(2,5)
arr.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [33]:
# indexing & slicing
arr[0]
arr[5:]

array([5, 6, 7, 8, 9])

In [37]:
#numpy 몇가지

#1. 2차원 배열에서 행렬의 각 행의 평균을 계산하는 코드를 작성하세요
#np.mean()

arr = np.array(([1,2,3],[4,5,6],[7,8,9]))

arr.shape
print(arr)

np.mean(arr, axis=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2., 5., 8.])

In [42]:
# 2. 1차원 배열에서 짝수 인덱스의 값을 출력하는 코드를 작성하세요

arr = np.array([1,2,3,4,5,6])

even_indexes = np.arange(0,arr.size,2)

print(arr[even_indexes])

[1 3 5]


In [44]:
# 3. 2차원 배열의 주 대각선상에 있는 원소들을 출력하는 코드를 작성하세요

arr = np.array(([1,2,3],[4,5,6],[7,8,9]))
arr.shape

#diag
np.diag(arr)

array([1, 5, 9])

In [47]:
#4 .2차원 배열에서 각 열의 표준편차를 계산하는 코드를 작성하세요
# 표준편차 --> np.std()

arr = np.array(([1,2,3],[4,5,6],[7,8,9]))

print(arr)

np.std(arr, axis=0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2.44948974, 2.44948974, 2.44948974])

In [49]:
#5 . 1차원 배열에서 중앙값(median)을 계산하는 코드를 작성하시오
arr = np.array([1,2,3,4,5])

np.median(arr)

3.0

In [51]:
#6 . 1차원 배열에서 원소의 값이 5 이상인 것들만 출력하는 코드를 작성하세요

arr = np.array([1,5,9,4,7,2,3,6])

arr[arr >= 5]

array([5, 9, 7, 6])

In [52]:
#7 . 1차원 배열에서 원소의 값이 3또는 5 인것들의 인덱스를 출력하는 코드를 작성하세요

arr = np.array([1,3,5,7,9,2,5,7,9,3,5])

np.where((arr==3)|(arr==5))

(array([ 1,  2,  6,  9, 10]),)